name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
        env:
          GIT_USER: Mulham-robotics
          USE_SSH: true
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
